Reference: https://geodacenter.github.io/workbook/6a_local_auto/lab6a.html#local-geary

# Univariate local geary

Interestingly, following [this equation](https://www.biomedware.com/files/documentation/spacestat/Statistics/Gearys_C/Geary_s_C_statistic.htm) which explicitly calls for standardization of input data. We also do NOT divide by 2.

$$ c_i = \sum_j w_{ij} (z_i - z_j)^2 $$ 

where: 

$z_i = x_i - \bar{x}$ and $z_j = x_j - \bar{x}$, and $w_{ij}$ are the elements of the row-standardized binary symmetric spatial weight matrix W. 

or, $$ c_i = (1/m^2) * \sum_j w_{ij} (x_i - x_j)^2 $$

where,

$$ m^2 = \sum_i (x_i−\bar{x})^2/n $$

## Load in example data

In [1]:
import libpysal as lp
import geopandas as gpd
from scipy import stats
import numpy as np
guerry = lp.examples.load_example('Guerry')
guerry_ds = gpd.read_file(guerry.get_path('Guerry.shp'))

In [2]:
wq = lp.weights.Queen.from_dataframe(guerry_ds)

In [3]:
wq[0]

{66: 1.0, 35: 1.0, 68: 1.0, 36: 1.0}

In [4]:
wq.transform = 'r'
wq[0]

{66: 0.25, 35: 0.25, 68: 0.25, 36: 0.25}

In [5]:
x = guerry_ds['Donatns']

print("x_i is", x[0])
print("x_j are", x[66], x[35], x[68], x[36])

x_i is 5098
x_j are 1983 4077 3710 3012


In [6]:
# Calculate score
zscore_x = (x - np.mean(x))/np.std(x)
zscore_x

0    -0.336188
1     0.450441
2     0.879023
3    -0.825375
4     0.049370
        ...   
80    1.512380
81    0.454785
82    1.467288
83   -0.555029
84   -0.506214
Name: Donatns, Length: 85, dtype: float64

# Build observed local geary values

In [7]:
adj_list = wq.to_adjlist(remove_symmetric=False)
adj_list.head()

focal  neighbor    weight
0      0        66  0.250000
1      0        35  0.250000
2      0        68  0.250000
3      0        36  0.250000
4      1        48  0.166667

In [8]:
import pandas as pd
zseries = pd.Series(zscore_x, index=wq.id_order)
zseries[0:5]

0   -0.336188
1    0.450441
2    0.879023
3   -0.825375
4    0.049370
Name: Donatns, dtype: float64

In [9]:
# Define z_i
zi = zseries.loc[adj_list.focal].values
zi[0:5]

array([-0.33618783, -0.33618783, -0.33618783, -0.33618783,  0.45044136])

In [10]:
# Define zj
zj = zseries.loc[adj_list.neighbor].values
zj[0:5]

array([-0.98050808, -0.54737594, -0.62328783, -0.76766521, -0.5709562 ])

In [11]:
(zi-zj)[0:5]

array([0.64432025, 0.21118812, 0.2871    , 0.43147738, 1.02139756])

In [12]:
#(zi-zj)**2

Multiply by spatial weights

In [13]:
sum(list(wq.weights.values()), [])

[0.25,
 0.25,
 0.25,
 0.25,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.25,
 0.25,
 0.25,
 0.25,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.3333333333333333,
 0.333333333333333

In [14]:
# sum(list(wq.weights.values()), []) * (zi-zj)**2

In [15]:
test = sum(list(wq.weights.values()), []) * (zi-zj)**2

In [16]:
test 

array([1.03787147e-01, 1.11501050e-02, 2.06066031e-02, 4.65431831e-02,
       1.73875498e-01, 4.46029515e-02, 9.23120791e-02, 8.24316606e-02,
       5.62651775e-02, 1.10526659e-01, 1.42169229e-02, 3.76156268e-01,
       4.10732150e-06, 1.93558239e-03, 4.03998774e-01, 1.78982952e-01,
       1.91294659e-01, 2.36509947e-02, 8.62708652e-04, 9.85757159e-05,
       1.18701948e-01, 2.55059545e-01, 2.43611071e-01, 4.83050957e-03,
       7.87731699e-04, 4.06844863e-04, 1.19408148e-03, 1.19796877e-04,
       8.05514201e-03, 2.30508994e-02, 8.46988022e-02, 8.92059030e-02,
       6.92770507e-02, 1.31434288e-02, 2.24980817e-02, 9.36161309e-01,
       1.07838582e-03, 1.40354877e-03, 9.76022807e-03, 3.81830297e-03,
       2.45842445e-02, 6.96194416e-03, 7.88605727e-03, 6.43214247e-03,
       7.49723084e-04, 7.02692918e-01, 4.75473805e-03, 1.10898230e-02,
       1.62392001e-04, 2.40344868e-02, 3.46212974e-04, 8.38114231e-03,
       1.43264902e-02, 7.68348646e-03, 2.59916438e-04, 1.62670468e-02,
      

In [17]:
# Create a df that uses the adjacency list focal values and the BBs counts
temp = pd.DataFrame(adj_list.focal.values, test).reset_index()
temp

index   0
0    0.103787   0
1    0.011150   0
2    0.020607   0
3    0.046543   0
4    0.173875   1
..        ...  ..
415  0.025788  84
416  0.326386  84
417  0.003818  84
418  0.001947  84
419  0.009025  84

[420 rows x 2 columns]

In [18]:
# Temporarily rename the columns
temp.columns = ['Eij', 'ID']
temp = temp.groupby(by='ID').sum()

In [19]:
temp.Eij.values[0:5]

array([0.18208704, 0.56001403, 0.97529461, 0.21590694, 0.61737256])

# Start building function

In [20]:
import numpy as np
import pandas as pd
import warnings
from scipy import sparse
from scipy import stats
from sklearn.base import BaseEstimator
import libpysal as lp
from esda.crand import (
    crand as _crand_plus,
    njit as _njit,
    _prepare_univariate
)

PERMUTATIONS = 999

class Local_Geary(BaseEstimator):
    """Local Geary - Univariate"""

    def __init__(self, connectivity=None, permutations=PERMUTATIONS, n_jobs=1, 
                 keep_simulations=True, seed=None):
        """
        connectivity     : scipy.sparse matrix object
                           the connectivity structure describing
                           the relationships between observed units.
                           Need not be row-standardized.
        permutations     : int
                           number of random permutations for calculation of pseudo
                           p_values
        n_jobs           : int
                           Number of cores to be used in the conditional randomisation. If -1,
                           all available cores are used.    
        keep_simulations : Boolean
                           (default=True)
                           If True, the entire matrix of replications under the null 
                           is stored in memory and accessible; otherwise, replications 
                           are not saved
        seed             : None/int
                           Seed to ensure reproducibility of conditional randomizations. 
                           Must be set here, and not outside of the function, since numba 
                           does not correctly interpret external seeds 
                           nor numpy.random.RandomState instances.  
                           
        Attributes
        ----------
        localG          : numpy array
                          array containing the observed univariate
                          Local Geary values.
        p_sim           : numpy array
                          array containing the simulated
                          p-values for each unit.
        """

        self.connectivity = connectivity
        self.permutations = permutations
        self.n_jobs = n_jobs
        self.keep_simulations = keep_simulations
        self.seed = seed

    def fit(self, x, n_jobs=1, permutations=999):
        """
        Arguments
        ---------
        x                : numpy.ndarray
                           array containing continuous data

        Returns
        -------
        the fitted estimator.

        Notes
        -----
        Technical details and derivations can be found in :cite:`Anselin1995`.

        Examples
        --------
        Guerry data replication GeoDa tutorial
        >>> import libpysal
        >>> import geopandas as gpd
        >>> guerry = lp.examples.load_example('Guerry')
        >>> guerry_ds = gpd.read_file(guerry.get_path('Guerry.shp'))
        >>> w = libpysal.weights.Queen.from_dataframe(guerry_ds)
        """
        x = np.asarray(x).flatten()

        w = self.connectivity
        w.transform = 'r'

        self.localG = self._statistic(x, w)

        if self.permutations:
            self.p_sim, self.rlocalG = _crand_plus(
                z=(x - np.mean(x))/np.std(x), 
                w=w, 
                observed=self.localG,
                permutations=permutations, 
                keep=True, 
                n_jobs=n_jobs,
                stat_func=_local_geary
            )
            
        del (self.keep_simulations, self.n_jobs, 
             self.permutations, self.seed, self.rlocalG,
             self.connectivity)

        return self

    @staticmethod
    def _statistic(x, w):
        # Caclulate z-scores for x
        zscore_x = (x - np.mean(x))/np.std(x)
        # Create focal (xi) and neighbor (zi) values
        adj_list = w.to_adjlist(remove_symmetric=False)
        zseries = pd.Series(zscore_x, index=wq.id_order)
        zi = zseries.loc[adj_list.focal].values
        zj = zseries.loc[adj_list.neighbor].values
        # Carry out local Geary calculation
        gs = sum(list(wq.weights.values()), []) * (zi-zj)**2
        # Reorganize data
        adj_list_gs = pd.DataFrame(adj_list.focal.values, gs).reset_index()
        adj_list_gs.columns = ['gs', 'ID']
        adj_list_gs = adj_list_gs.groupby(by='ID').sum()
        
        localG = adj_list_gs.gs.values
        
        return (localG)

# --------------------------------------------------------------
# Conditional Randomization Function Implementations
# --------------------------------------------------------------

# Note: does not using the scaling parameter

@_njit(fastmath=True)
def _local_geary(i, z, permuted_ids, weights_i, scaling):
    zi, zrand = _prepare_univariate(i, z, permuted_ids, weights_i)
    return (zi-zrand)**2 @ weights_i

In [21]:
functest = Local_Geary(connectivity=wq).fit(x)

In [22]:
functest.localG

array([1.82087039e-01, 5.60014026e-01, 9.75294606e-01, 2.15906938e-01,
       6.17372564e-01, 3.84450059e-02, 2.43181756e-01, 9.71802819e-01,
       4.06447101e-02, 7.24722785e-01, 6.30952854e-02, 2.42104497e-02,
       1.59496916e+01, 9.29326006e-01, 9.65188634e-01, 1.32383286e+00,
       3.31775497e-01, 2.99446505e+00, 9.43946814e-01, 2.99570159e+00,
       3.66702291e-01, 2.09592365e+00, 1.46515861e+00, 1.82118455e-01,
       3.10216680e+00, 5.43063937e-01, 5.74532559e+00, 4.79160197e-02,
       1.58993089e-01, 7.18327253e-01, 1.24297849e+00, 8.72629331e-02,
       7.52809650e-01, 4.56515485e-01, 3.86766562e-01, 1.17632604e-01,
       6.90884685e-01, 2.87206102e+00, 4.10455112e-01, 4.04349959e-01,
       1.14211758e-01, 9.59519953e-01, 3.51347976e-01, 7.30240974e-01,
       4.40370938e-01, 7.20360356e-02, 1.66241706e+00, 5.83258909e+00,
       2.30332507e-01, 4.38369688e-01, 8.41461470e-01, 1.52959486e+00,
       4.32157479e-02, 2.08325903e+00, 1.19722984e+00, 1.28169257e+00,
      

In [23]:
functest.p_sim

array([0.2  , 0.067, 0.074, 0.166, 0.448, 0.006, 0.158, 0.424, 0.019,
       0.3  , 0.015, 0.01 , 0.143, 0.444, 0.005, 0.025, 0.003, 0.143,
       0.316, 0.075, 0.002, 0.191, 0.324, 0.096, 0.084, 0.346, 0.037,
       0.011, 0.027, 0.283, 0.239, 0.009, 0.488, 0.003, 0.122, 0.079,
       0.322, 0.201, 0.285, 0.153, 0.04 , 0.367, 0.194, 0.499, 0.264,
       0.006, 0.24 , 0.035, 0.127, 0.228, 0.275, 0.268, 0.018, 0.078,
       0.422, 0.331, 0.072, 0.262, 0.042, 0.016, 0.265, 0.42 , 0.424,
       0.12 , 0.413, 0.156, 0.068, 0.125, 0.292, 0.17 , 0.092, 0.192,
       0.012, 0.23 , 0.005, 0.141, 0.036, 0.029, 0.01 , 0.001, 0.036,
       0.473, 0.002, 0.37 , 0.252])

## Start working on inference (note: now implemented above)

### 'New' `_crand()` engine

In [35]:
from esda.crand import (
    crand as _crand_plus,
    njit as _njit,
    _prepare_univariate
)

In [36]:
@_njit(fastmath=True)
def _local_geary(i, z, permuted_ids, weights_i, scaling):
    zi, zrand = _prepare_univariate(i, z, permuted_ids, weights_i)
    return (zi-zrand)**2 @ weights_i

In [96]:
p_sim, rlocalG = _crand_plus(z=np.array(zscore_x), w=wq, observed=np.array(functest.localG), 
            permutations=999, keep=True, n_jobs=1, 
            stat_func=_local_geary)

print(p_sim)
print(rlocalG)

[0.018 0.001 0.001 0.037 0.052 0.001 0.011 0.328 0.001 0.056 0.001 0.002
 0.001 0.1   0.001 0.001 0.001 0.001 0.015 0.221 0.001 0.166 0.444 0.01
 0.003 0.049 0.006 0.001 0.001 0.038 0.329 0.001 0.001 0.001 0.001 0.003
 0.075 0.022 0.005 0.009 0.002 0.014 0.004 0.041 0.029 0.001 0.082 0.191
 0.006 0.036 0.044 0.312 0.001 0.003 0.163 0.001 0.009 0.006 0.043 0.01
 0.034 0.357 0.084 0.335 0.006 0.296 0.008 0.008 0.03  0.024 0.058 0.018
 0.001 0.034 0.001 0.003 0.003 0.001 0.002 0.001 0.002 0.001 0.001 0.107
 0.068]
[[ 4.75042754  7.62826988  0.95914326 ...  3.46963549  6.37275009
   2.27667795]
 [ 6.58741518  8.14013558  3.80981896 ... 18.92770098  7.17118703
   3.0485724 ]
 [10.48108682 11.37655842  7.86004595 ... 18.59384625 10.55299537
   6.18978548]
 ...
 [28.177093   14.07050045  6.61259349 ... 19.24718966 18.72051356
  16.3878716 ]
 [24.42238711  3.76764772  9.72980253 ...  3.46537774  8.34320254
  20.1936107 ]
 [23.93203757  3.43491617  6.71080041 ...  3.10360435  8.00196439
  19.45

# Multivariate Local Geary

$$ c_i = \sum_{h=1}^m \sum_j w_{ij} (x_{hi} - x_{hj})^2 $$

Load in the sample data

In [97]:
import libpysal as lp
import geopandas as gpd
from scipy import stats
import pandas as pd
guerry = lp.examples.load_example('Guerry')
guerry_ds = gpd.read_file(guerry.get_path('Guerry.shp'))

In [98]:
wq = lp.weights.Queen.from_dataframe(guerry_ds)

In [99]:
x = guerry_ds['Donatns']
y = guerry_ds['Suicids']

In [101]:
variables = [x,y]

Standardize each variable

In [102]:
from scipy import stats
zseries = [stats.zscore(i) for i in variables]

Build the adj lists

In [103]:
adj_list = wq.to_adjlist(remove_symmetric=False)

In [104]:
# The zseries
zseries = [pd.Series(i, index=wq.id_order) for i in zseries]

In [105]:
zseries

[0    -0.336188
 1     0.450441
 2     0.879023
 3    -0.825375
 4     0.049370
         ...   
 80    1.512380
 81    0.454785
 82    1.467288
 83   -0.555029
 84   -0.506214
 Length: 85, dtype: float64,
 0    -0.047195
 1    -0.756433
 2     2.478379
 3    -0.711499
 4    -0.649766
         ...   
 80    1.004270
 81   -0.468369
 82   -0.096441
 83   -0.111387
 84   -0.757774
 Length: 85, dtype: float64]

In [106]:
# The focal values
focal = [zseries[i].loc[adj_list.focal].values for
         i in range(len(variables))]
# The neighbor values
neighbor = [zseries[i].loc[adj_list.neighbor].values for
            i in range(len(variables))]

In [150]:
np.array(focal)[0][0]

-0.3361878263899247

In [154]:
np.array(neighbor)[0][0]

-0.9805080804028404

In [161]:
(np.array(focal)[0][0] - np.array(neighbor)[0][0])**2

0.4151485897312682

In [160]:
temp = (np.array(focal) - np.array(neighbor))**2
temp[0][0]

0.4151485897312682

In [107]:
gs = sum(list(wq.weights.values()), []) * (np.array(focal) - np.array(neighbor))**2

In [108]:
temp = pd.DataFrame(gs).T

In [109]:
temp['ID'] = adj_list.focal.values

In [110]:
adj_list_gs = temp.groupby(by='ID').sum()
adj_list_gs.head()

0          1
ID                     
0   0.728348   0.502200
1   3.360084   0.282630
2   5.851768  29.604873
3   0.863628   0.121489
4   1.852118   0.475642

In [111]:
k = len(variables)
k

2

In [112]:
adj_list_gs.sum(axis=1)/k

ID
0      0.615274
1      1.821357
2     17.728320
3      0.492558
4      1.163880
        ...    
80     6.629720
81     3.154587
82     3.872022
83     4.307689
84     1.080905
Length: 85, dtype: float64

In [116]:
import numpy as np
import pandas as pd
import warnings
from scipy import sparse
from scipy import stats
from sklearn.base import BaseEstimator
import libpysal as lp

PERMUTATIONS=999

class Local_Geary_MV(BaseEstimator):
    """Local Geary - Multivariate"""

    def __init__(self, connectivity=None, permutations=PERMUTATIONS, n_jobs=1, 
                 keep_simulations=True, seed=None):
        """
        connectivity     : scipy.sparse matrix object
                           the connectivity structure describing
                           the relationships between observed units.
                           Need not be row-standardized.
        permutations     : int
                           number of random permutations for calculation of pseudo
                           p_values
        n_jobs           : int
                           Number of cores to be used in the conditional randomisation. If -1,
                           all available cores are used.    
        keep_simulations : Boolean
                           (default=True)
                           If True, the entire matrix of replications under the null 
                           is stored in memory and accessible; otherwise, replications 
                           are not saved
        seed             : None/int
                           Seed to ensure reproducibility of conditional randomizations. 
                           Must be set here, and not outside of the function, since numba 
                           does not correctly interpret external seeds 
                           nor numpy.random.RandomState instances.  
                           
        Attributes
        ----------
        localG          : numpy array
                          array containing the observed multivariate
                          Local Geary values.
        p_sim           : numpy array
                          array containing the simulated
                          p-values for each unit.
        """

        self.connectivity = connectivity
        self.permutations = permutations
        self.n_jobs = n_jobs
        self.keep_simulations = keep_simulations
        self.seed = seed

    def fit(self, variables, n_jobs=1, permutations=999):
        """
        Arguments
        ---------
        variables        : numpy.ndarray
                           array containing continuous data

        Returns
        -------
        the fitted estimator.

        Notes
        -----
        Technical details and derivations can be found in :cite:`Anselin1995`.

        Examples
        --------
        Guerry data replication GeoDa tutorial
        >>> import libpysal
        >>> import geopandas as gpd
        >>> guerry = lp.examples.load_example('Guerry')
        >>> guerry_ds = gpd.read_file(guerry.get_path('Guerry.shp'))
        >>> w = libpysal.weights.Queen.from_dataframe(guerry_ds)
        """
        self.variables = np.array(variables, dtype='float')

        w = self.connectivity
        w.transform = 'r'

        self.localG = self._statistic(variables, w)

        if permutations:
            pass

        return self

    @staticmethod
    def _statistic(variables, w):
        # Caclulate z-scores for input variables
        zseries = [stats.zscore(i) for i in variables]
        # Define denominator adjustment
        k = len(variables)
        # Create focal and neighbor values
        adj_list = w.to_adjlist(remove_symmetric=False)
        zseries = [pd.Series(i, index=wq.id_order) for i in zseries]
        focal = [zseries[i].loc[adj_list.focal].values for
                 i in range(len(variables))]
        neighbor = [zseries[i].loc[adj_list.neighbor].values for
                    i in range(len(variables))]
        # Carry out local Geary calculation
        gs = sum(list(wq.weights.values()), []) * \
        (np.array(focal) - np.array(neighbor))**2
        # Reorganize data
        temp = pd.DataFrame(gs).T
        temp['ID'] = adj_list.focal.values
        adj_list_gs = temp.groupby(by='ID').sum()
        localG = adj_list_gs.sum(axis=1)/k
        
        return (localG)

# --------------------------------------------------------------
# Conditional Randomization Function Implementations
# --------------------------------------------------------------

# Note: does not using the scaling parameter

@_njit(fastmath=True)
def _local_geary(i, z, permuted_ids, weights_i, scaling):
    zi, zrand = _prepare_univariate(i, z, permuted_ids, weights_i)
    return (zi-zrand)**2 @ weights_i    

In [117]:
functest = Local_Geary_MV(connectivity=wq).fit([x,y])
functest.localG

ID
0     0.153819
1     0.303560
2     2.954720
3     0.123140
4     0.387960
        ...   
80    1.657430
81    0.525764
82    0.645337
83    0.717948
84    0.216181
Length: 85, dtype: float64

## Working on inference

In [ ]:
from esda.crand import (
    crand as _crand_plus,
    njit as _njit,
    _prepare_univariate
)

In [ ]:
@_njit(fastmath=True)
def _local_geary(i, z, permuted_ids, weights_i, scaling):
    zi, zrand = _prepare_univariate(i, z, permuted_ids, weights_i)
    return (zi-zrand)**2 @ weights_i

In [ ]:
p_sim, rlocalG = _crand_plus(z=np.array(x, dtype='float'), w=wq, observed=np.array(functest.localG), 
            permutations=999, keep=True, n_jobs=1, 
            stat_func=_local_geary)

print(p_sim)
print(rlocalG)

In [197]:
x_zscore = stats.zscore(x)
y_zscore = stats.zscore(y)

In [222]:
result = zip(x_zscore, y_zscore)
result = list(result)
result = np.array(result)
result[0:5]

array([[-0.33618783, -0.04719523],
       [ 0.45044136, -0.75643306],
       [ 0.87902293,  2.47837872],
       [-0.82537479, -0.71149891],
       [ 0.0493701 , -0.64976635]])

In [272]:
permutations = 999
# Get length based on first variable
n = len(result)
localGs = np.zeros((n, permutations))
n_1 = n - 1
prange = list(range(permutations))
k = wq.max_neighbors + 1
nn = n - 1
rids = np.array([np.random.permutation(nn)[0:k] for i in prange])
ids = np.arange(wq.n)
ido = wq.id_order
w = [wq.weights[ido[i]] for i in ids]
wc = [wq.cardinalities[ido[i]] for i in ids]


Note: below **are** z-score standardized

In [273]:
wq.weights[0]

[0.25, 0.25, 0.25, 0.25]

In [302]:
for i in range(wq.n):
    idsi = ids[ids != i]
    np.random.shuffle(idsi)
    tmp = result[idsi[rids[:, 0:wc[i]]]]
    # define zi?
    zi = result[i][0]
    # define zrand?
    zrand = tmp[i][:,1]
    # Subtract and square?
    temp = (zi - zrand)**2
    # Multiply by weights?
    localGs[i] = (temp * wq.weights[i]).sum(0)
    #joins[i] = result[i] * (w[i] * tmp).sum(1)
    #localGs[i] = ((result[i,0] - tmp2)**2 * wq.weights[i][0]).sum(0)
rlocalGs = localGs

In [303]:
rlocalGs

array([[0.26721819, 0.26721819, 0.26721819, ..., 0.26721819, 0.26721819,
        0.26721819],
       [0.91312819, 0.91312819, 0.91312819, ..., 0.91312819, 0.91312819,
        0.91312819],
       [1.82447727, 1.82447727, 1.82447727, ..., 1.82447727, 1.82447727,
        1.82447727],
       ...,
       [3.58780957, 3.58780957, 3.58780957, ..., 3.58780957, 3.58780957,
        3.58780957],
       [0.58341704, 0.58341704, 0.58341704, ..., 0.58341704, 0.58341704,
        0.58341704],
       [1.0249522 , 1.0249522 , 1.0249522 , ..., 1.0249522 , 1.0249522 ,
        1.0249522 ]])

In [304]:
np.transpose(rlocalGs)

array([[0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ],
       [0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ],
       [0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ],
       ...,
       [0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ],
       [0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ],
       [0.26721819, 0.91312819, 1.82447727, ..., 3.58780957, 0.58341704,
        1.0249522 ]])

In [305]:
sim = np.transpose(rlocalGs)
print(sim[0])
print(sim[1])

[ 0.26721819  0.91312819  1.82447727  0.68581343  0.44568645  1.76767583
  0.80258989  0.66230655  0.93780899  0.10340713  1.52159122  0.21379009
 18.62855478  3.29942888  2.68765839  2.98302473  1.09152339  4.06345528
  0.64971154  4.62442999  1.6879433   0.36593487  0.043572    1.44375429
  2.94941027  0.9777734  13.85946968  2.12471681  0.27385553  2.29783322
  2.3771586   6.39740712  1.95627096  2.27994365  0.60679318  2.78409057
  1.03203037  2.59519992  0.3972223   1.42431346  0.74326897  0.63424248
  0.661845    0.8692988   0.14449406  2.0494169   0.84148845  0.58049004
  0.25295547  0.89033802  5.65270587  0.35507219  2.4715445   3.93810866
  0.70459891  0.80782293  4.89409064  0.81445492  0.85977211  3.85000826
  1.40205346  0.05687917  0.39572456  4.30201367  3.84110723  0.0791623
  0.20380214  2.94112877  0.23819749  0.90717012  0.43957761  5.60299738
  2.82517195  0.4796973   6.04758742  2.13357271  0.77285649  0.80810683
  2.0723401   1.18625783  3.28329331  0.6283649   3.

In [ ]:
sim[0]

In [311]:
larger[False]

array([], dtype=int64)

In [308]:
above = sim[0] >= functest.localG
larger = above.sum(0)
low_extreme = (permutations - larger) < larger
larger[low_extreme] = permutations - larger[low_extreme]
p_sim = (larger + 1.0) / (permutations + 1.0)
p_sim

TypeError: 'numpy.int64' object does not support item assignment

In [251]:
temp2

0.22308151691270237