Scratch notebook of [issues raised on Github](https://github.com/jeffcsauer/GSOC2020).

# [Issue 2](https://github.com/jeffcsauer/GSOC2020/issues/2)

In [30]:
import libpysal
import geopandas

In [31]:
df = geopandas.read_file('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/neighborhoods.gpkg')
w = libpysal.weights.Rook.from_dataframe(df)

In [34]:
# My solution
import numpy as np
Wrs = [round(np.sum(list(w[i].values()))) for i in range(len(df.hood_id))]
Wrs

[3.0,
 3.0,
 5.0,
 3.0,
 5.0,
 3.0,
 5.0,
 2.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 3.0,
 4.0,
 5.0,
 2.0,
 6.0,
 6.0,
 5.0,
 8.0,
 5.0,
 4.0,
 6.0,
 3.0,
 6.0,
 5.0,
 7.0,
 4.0,
 6.0,
 5.0,
 3.0,
 5.0,
 5.0,
 5.0,
 7.0,
 3.0,
 5.0,
 2.0,
 5.0]

In [38]:
# Levi's suggestion
row_sums = np.asarray(w.sparse.sum(axis=1)).flatten()
row_sums

array([3., 3., 5., 3., 5., 3., 5., 2., 5., 4., 5., 4., 5., 4., 5., 5., 4.,
       3., 4., 5., 2., 6., 6., 5., 8., 5., 4., 6., 3., 6., 5., 7., 4., 6.,
       5., 3., 5., 5., 5., 7., 3., 5., 2., 5.])

A terrific suggestion and much more elegant!

# [Issue 3](https://github.com/jeffcsauer/GSOC2020/issues/3)

In [30]:
import libpysal
import geopandas
import numpy as np
df = geopandas.read_file('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/neighborhoods.gpkg')
w = libpysal.weights.Rook.from_dataframe(df)

In [31]:
w[0]

{25: 1.0, 3: 1.0, 21: 1.0}

In [32]:
# Levi's solution
(w.sparse**2).sum(axis=1)

matrix([[14.],
        [14.],
        [21.],
        [13.],
        [31.],
        [14.],
        [27.],
        [12.],
        [23.],
        [14.],
        [28.],
        [16.],
        [22.],
        [21.],
        [21.],
        [23.],
        [16.],
        [13.],
        [22.],
        [32.],
        [ 8.],
        [27.],
        [32.],
        [29.],
        [44.],
        [22.],
        [16.],
        [28.],
        [12.],
        [33.],
        [22.],
        [34.],
        [20.],
        [37.],
        [27.],
        [16.],
        [29.],
        [21.],
        [26.],
        [37.],
        [14.],
        [22.],
        [10.],
        [25.]])

In [33]:
[np.sum(np.array(list(w[i].values()))**2) for i in w.id_order]

[3.0,
 3.0,
 5.0,
 3.0,
 5.0,
 3.0,
 5.0,
 2.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 3.0,
 4.0,
 5.0,
 2.0,
 6.0,
 6.0,
 5.0,
 8.0,
 5.0,
 4.0,
 6.0,
 3.0,
 6.0,
 5.0,
 7.0,
 4.0,
 6.0,
 5.0,
 3.0,
 5.0,
 5.0,
 5.0,
 7.0,
 3.0,
 5.0,
 2.0,
 5.0]

Row standardize the weights.

In [34]:
w.transform = 'r'
w[0]

{25: 0.3333333333333333, 3: 0.3333333333333333, 21: 0.3333333333333333}

In [38]:
# Levi's solution
print((w.sparse**2).sum(axis=1))

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [37]:
print([np.sum(np.array(list(w[i].values()))**2) for i in w.id_order])

[0.3333333333333333, 0.3333333333333333, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.5, 0.20000000000000004, 0.25, 0.20000000000000004, 0.25, 0.20000000000000004, 0.25, 0.20000000000000004, 0.20000000000000004, 0.25, 0.3333333333333333, 0.25, 0.20000000000000004, 0.5, 0.16666666666666669, 0.16666666666666669, 0.20000000000000004, 0.125, 0.20000000000000004, 0.25, 0.16666666666666669, 0.3333333333333333, 0.16666666666666669, 0.20000000000000004, 0.14285714285714285, 0.25, 0.16666666666666669, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.20000000000000004, 0.20000000000000004, 0.14285714285714285, 0.3333333333333333, 0.20000000000000004, 0.5, 0.20000000000000004]
