Scratch notebook of [issues raised on Github](https://github.com/jeffcsauer/GSOC2020).

# [Issue 2](https://github.com/jeffcsauer/GSOC2020/issues/2)

In [30]:
import libpysal
import geopandas

In [31]:
df = geopandas.read_file('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/neighborhoods.gpkg')
w = libpysal.weights.Rook.from_dataframe(df)

In [34]:
# My solution
import numpy as np
Wrs = [round(np.sum(list(w[i].values()))) for i in range(len(df.hood_id))]
Wrs

[3.0,
 3.0,
 5.0,
 3.0,
 5.0,
 3.0,
 5.0,
 2.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 3.0,
 4.0,
 5.0,
 2.0,
 6.0,
 6.0,
 5.0,
 8.0,
 5.0,
 4.0,
 6.0,
 3.0,
 6.0,
 5.0,
 7.0,
 4.0,
 6.0,
 5.0,
 3.0,
 5.0,
 5.0,
 5.0,
 7.0,
 3.0,
 5.0,
 2.0,
 5.0]

In [38]:
# Levi's suggestion
row_sums = np.asarray(w.sparse.sum(axis=1)).flatten()
row_sums

array([3., 3., 5., 3., 5., 3., 5., 2., 5., 4., 5., 4., 5., 4., 5., 5., 4.,
       3., 4., 5., 2., 6., 6., 5., 8., 5., 4., 6., 3., 6., 5., 7., 4., 6.,
       5., 3., 5., 5., 5., 7., 3., 5., 2., 5.])

A terrific suggestion and much more elegant!

# [Issue 3](https://github.com/jeffcsauer/GSOC2020/issues/3)

In [30]:
import libpysal
import geopandas
import numpy as np
df = geopandas.read_file('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/neighborhoods.gpkg')
w = libpysal.weights.Rook.from_dataframe(df)

In [31]:
w[0]

{25: 1.0, 3: 1.0, 21: 1.0}

In [32]:
# Levi's solution
(w.sparse**2).sum(axis=1)

matrix([[14.],
        [14.],
        [21.],
        [13.],
        [31.],
        [14.],
        [27.],
        [12.],
        [23.],
        [14.],
        [28.],
        [16.],
        [22.],
        [21.],
        [21.],
        [23.],
        [16.],
        [13.],
        [22.],
        [32.],
        [ 8.],
        [27.],
        [32.],
        [29.],
        [44.],
        [22.],
        [16.],
        [28.],
        [12.],
        [33.],
        [22.],
        [34.],
        [20.],
        [37.],
        [27.],
        [16.],
        [29.],
        [21.],
        [26.],
        [37.],
        [14.],
        [22.],
        [10.],
        [25.]])

In [33]:
[np.sum(np.array(list(w[i].values()))**2) for i in w.id_order]

[3.0,
 3.0,
 5.0,
 3.0,
 5.0,
 3.0,
 5.0,
 2.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 3.0,
 4.0,
 5.0,
 2.0,
 6.0,
 6.0,
 5.0,
 8.0,
 5.0,
 4.0,
 6.0,
 3.0,
 6.0,
 5.0,
 7.0,
 4.0,
 6.0,
 5.0,
 3.0,
 5.0,
 5.0,
 5.0,
 7.0,
 3.0,
 5.0,
 2.0,
 5.0]

Row standardize the weights.

In [34]:
w.transform = 'r'
w[0]

{25: 0.3333333333333333, 3: 0.3333333333333333, 21: 0.3333333333333333}

In [38]:
# Levi's solution
print((w.sparse**2).sum(axis=1))

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [37]:
print([np.sum(np.array(list(w[i].values()))**2) for i in w.id_order])

[0.3333333333333333, 0.3333333333333333, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.5, 0.20000000000000004, 0.25, 0.20000000000000004, 0.25, 0.20000000000000004, 0.25, 0.20000000000000004, 0.20000000000000004, 0.25, 0.3333333333333333, 0.25, 0.20000000000000004, 0.5, 0.16666666666666669, 0.16666666666666669, 0.20000000000000004, 0.125, 0.20000000000000004, 0.25, 0.16666666666666669, 0.3333333333333333, 0.16666666666666669, 0.20000000000000004, 0.14285714285714285, 0.25, 0.16666666666666669, 0.20000000000000004, 0.3333333333333333, 0.20000000000000004, 0.20000000000000004, 0.20000000000000004, 0.14285714285714285, 0.3333333333333333, 0.20000000000000004, 0.5, 0.20000000000000004]


# ESDA Issue #86

In [31]:
from pysal.lib import weights
from pysal.explore import esda
from scipy import sparse

adjacency = sparse.csc_matrix([[1,1,0],
                               [1,1,1],
                               [0,1,1]])

w = weights.WSP(adjacency).to_W()

data = [1,2,3]

esda.Moran_Local(data, w)

ValueError: dimension mismatch

# Local Gamma


In [1]:
"""
Gamma index for spatial autocorrelation


"""
__author__ = "Luc Anselin <luc.anselin@asu.edu> Serge Rey <sjsrey@gmail.com>"

import numpy as np
from libpysal.weights.spatial_lag import lag_spatial
import warnings

__all__ = ['Gamma']

PERMUTATIONS = 999


class Gamma(object):
    """Gamma index for spatial autocorrelation


    Parameters
    ----------

    y               : array
                      variable measured across n spatial units
    w               : W
                      spatial weights instance
                      can be binary or row-standardized
    operation       : {'c', 's', 'a'}
                      attribute similarity function where,
                      'c' cross product
                      's' squared difference
                      'a' absolute difference
    standardize     : {False, True}
                      standardize variables first
                      False, keep as is
                      True, standardize to mean zero and variance one
    permutations    : int
                      number of random permutations for calculation of pseudo-p_values

    Attributes
    ----------
    y            : array
                   original variable
    w            : W
                   original w object
    op           : {'c', 's', 'a'}
                   attribute similarity function, as per parameters
                   attribute similarity function
    stand        : {False, True}
                   standardization
    permutations : int
                   number of permutations
    gamma        : float
                   value of Gamma index
    sim_g        : array
                   (if permutations>0)
                   vector of Gamma index values for permuted samples
    p_sim_g      : array
                   (if permutations>0)
                   p-value based on permutations (one-sided)
                   null: spatial randomness
                   alternative: the observed Gamma is more extreme than under randomness
                   implemented as a two-sided test
    mean_g       : float
                   average of permuted Gamma values
    min_g        : float
                   minimum of permuted Gamma values
    max_g        : float
                   maximum of permuted Gamma values


    Examples
    --------

    use same example as for join counts to show similarity

    >>> import libpysal, numpy as np
    >>> from esda.gamma import Gamma
    >>> w = libpysal.weights.lat2W(4,4)
    >>> y=np.ones(16)
    >>> y[0:8]=0
    >>> np.random.seed(12345)
    >>> g = Gamma(y,w)
    >>> g.g
    20.0
    >>> round(g.g_z, 3)
    3.188
    >>> round(g.p_sim_g, 3)
    0.003
    >>> g.min_g
    0.0
    >>> g.max_g
    20.0
    >>> g.mean_g
    11.093093093093094
    >>> np.random.seed(12345)
    >>> g1 = Gamma(y,w,operation='s')
    >>> g1.g
    8.0
    >>> round(g1.g_z, 3)
    -3.706
    >>> g1.p_sim_g
    0.001
    >>> g1.min_g
    14.0
    >>> g1.max_g
    48.0
    >>> g1.mean_g
    25.623623623623622
    >>> np.random.seed(12345)
    >>> g2 = Gamma(y,w,operation='a')
    >>> g2.g
    8.0
    >>> round(g2.g_z, 3)
    -3.706
    >>> g2.p_sim_g
    0.001
    >>> g2.min_g
    14.0
    >>> g2.max_g
    48.0
    >>> g2.mean_g
    25.623623623623622
    >>> np.random.seed(12345)
    >>> g3 = Gamma(y,w,standardize=True)
    >>> g3.g
    32.0
    >>> round(g3.g_z, 3)
    3.706
    >>> g3.p_sim_g
    0.001
    >>> g3.min_g
    -48.0
    >>> g3.max_g
    20.0
    >>> g3.mean_g
    -3.2472472472472473
    >>> np.random.seed(12345)
    >>> def func(z,i,j):
    ...     q = z[i]*z[j]
    ...     return q
    ...
    >>> g4 = Gamma(y,w,operation=func)
    >>> g4.g
    20.0
    >>> round(g4.g_z, 3)
    3.188
    >>> round(g4.p_sim_g, 3)
    0.003

    Notes
    -----

    For further technical details see :cite:`Hubert_1981`.



    """
    def __init__(self, y, w, operation='c', standardize=False, permutations=PERMUTATIONS):
        if isinstance(standardize, str):
            standardize = standardize.lower() == 'yes'
            warnings.warn('Use True/False for standardize. The option to'
                          ' provide "yes"/"no" will be deprecated in PySAL 2.2.' )
        y = np.asarray(y).flatten()
        self.w = w
        self.y = y
        self.op = operation
        self.stand = standardize
        self.permutations = permutations
        if self.stand:
            ym = np.mean(self.y)
            ysd = np.std(self.y)
            ys = (self.y - ym) / ysd
            self.y = ys
        self.g = self.__calc(self.y, self.op)

        if permutations:
            sim = [self.__calc(np.random.permutation(self.y), self.op)
                   for i in range(permutations)]
            self.sim_g = np.array(sim)
            self.min_g = np.min(self.sim_g)
            self.mean_g = np.mean(self.sim_g)
            self.max_g = np.max(self.sim_g)
            p_sim_g = self.__pseudop(self.sim_g, self.g)
            self.p_sim_g = p_sim_g
            self.g_z = (self.g - self.mean_g) / np.std(self.sim_g)

    @property
    def _statistic(self):
        return self.g

    @property
    def  p_sim(self):
        """new name to fit with Moran module"""
        return self.p_sim_g

    def __calc(self, z, op):
        if op == 'c':     # cross-product
            zl = lag_spatial(self.w, z)
            g = (z * zl).sum()
        elif op == 's':   # squared difference
            zs = np.zeros(z.shape)
            z2 = z ** 2
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * (z2[i] - 2.0 * z[i] * z[
                    j] + z2[j]) for j, wij in zw])
            g = zs.sum()
        elif op == 'a':    # absolute difference
            zs = np.zeros(z.shape)
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * abs(z[i] - z[j]) for j, wij in zw])
            g = zs.sum()
        else:              # any previously defined function op
            zs = np.zeros(z.shape)
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * op(z, i, j) for j, wij in zw])
            g = zs.sum()
        return g

    def __pseudop(self, sim, g):
        above = sim >= g
        larger = above.sum()
        psim = (larger + 1.) / (self.permutations + 1.)
        if psim > 0.5:
            psim = (self.permutations - larger + 1.) / (self.permutations + 1.)
        return psim

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\libpysal\weights\util.py:19: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')


In [3]:
import libpysal, numpy as np
from esda.gamma import Gamma

w = libpysal.weights.lat2W(4,4)
y=np.ones(16)
y[0:8]=0
np.random.seed(12345)
g = Gamma(y,w)
g.g

20.0

In [23]:
zl = lag_spatial(w, y); zl

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 3., 3., 2., 2., 3., 3., 2.])

In [27]:
g = (y * zl).sum(); g

20.0

Local statistic for each unit should sum to 20.

In [4]:
"""
Local gamma index for spatial autocorrelation


"""
__author__ = "Luc Anselin <luc.anselin@asu.edu> Serge Rey <sjsrey@gmail.com>"

import numpy as np
from libpysal.weights.spatial_lag import lag_spatial
import warnings

__all__ = ['Local_Gamma']

PERMUTATIONS = 999


class Local_Gamma(object):
    """Local Gamma index for spatial autocorrelation


    Parameters
    ----------

    y               : array
                      variable measured across n spatial units
    w               : W
                      spatial weights instance
                      can be binary or row-standardized
    operation       : {'c', 's', 'a'}
                      attribute similarity function where,
                      'c' cross product
                      's' squared difference
                      'a' absolute difference
    standardize     : {False, True}
                      standardize variables first
                      False, keep as is
                      True, standardize to mean zero and variance one
    permutations    : int
                      number of random permutations for calculation of pseudo-p_values

    Attributes
    ----------
    y            : array
                   original variable
    w            : W
                   original w object
    op           : {'c', 's', 'a'}
                   attribute similarity function, as per parameters
                   attribute similarity function
    stand        : {False, True}
                   standardization
    permutations : int
                   number of permutations
    gamma        : float
                   value of Gamma index
    sim_g        : array
                   (if permutations>0)
                   vector of Gamma index values for permuted samples
    p_sim_g      : array
                   (if permutations>0)
                   p-value based on permutations (one-sided)
                   null: spatial randomness
                   alternative: the observed Gamma is more extreme than under randomness
                   implemented as a two-sided test
    mean_g       : float
                   average of permuted Gamma values
    min_g        : float
                   minimum of permuted Gamma values
    max_g        : float
                   maximum of permuted Gamma values

    """
    def __init__(self, y, w, operation='c', standardize=False, permutations=PERMUTATIONS):
        if isinstance(standardize, str):
            standardize = standardize.lower() == 'yes'
            warnings.warn('Use True/False for standardize. The option to'
                          ' provide "yes"/"no" will be deprecated in PySAL 2.2.' )
        y = np.asarray(y).flatten()
        self.w = w
        self.y = y
        self.n = len(y)
        self.op = operation
        self.stand = standardize
        self.permutations = permutations
        if self.stand:
            ym = np.mean(self.y)
            ysd = np.std(self.y)
            ys = (self.y - ym) / ysd
            self.y = ys
        self.g = self.__calc(self.y, self.op)

        if permutations:
            self.__crand()
            sim = np.transpose(self.localgs)
            above = sim >= self.g
            larger = above.sum(0)
            low_extreme = (self.permutations - larger) < larger
            larger[low_extreme] = self.permutations - larger[low_extreme]
            self.p_sim = (larger + 1.0) / (permutations + 1.0)
            #print(p_sim)
    
    @property
    def _statistic(self):
        return self.g

    def __calc(self, z, op):
        if op == 'c':     # cross-product
            zl = lag_spatial(self.w, z)
            # Remove the suffix .sum()
            g = z * zl
        elif op == 's':   # squared difference
            zs = np.zeros(z.shape)
            z2 = z ** 2
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * (z2[i] - 2.0 * z[i] * z[
                    j] + z2[j]) for j, wij in zw])
            # Removed the suffix .sum()    
            g = zs
        elif op == 'a':    # absolute difference
            zs = np.zeros(z.shape)
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * abs(z[i] - z[j]) for j, wij in zw])
            # Removed the suffix .sum()    
            g = zs
        else:              # any previously defined function op
            zs = np.zeros(z.shape)
            for i, i0 in enumerate(self.w.id_order):
                neighbors = self.w.neighbor_offsets[i0]
                wijs = self.w.weights[i0]
                zw = list(zip(neighbors, wijs))
                zs[i] = sum([wij * op(z, i, j) for j, wij in zw])
            # Removed the suffix .sum()    
            g = zs
        return g
    
    def __crand(self):
        """
        conditional randomization
        for observation i with ni neighbors,  the candidate set cannot include
        i (we don't want i being a neighbor of i). we have to sample without
        replacement from a set of ids that doesn't include i. numpy doesn't
        directly support sampling wo replacement and it is expensive to
        implement this. instead we omit i from the original ids,  permute the
        ids and take the first ni elements of the permuted ids as the
        neighbors to i in each randomization.
        """
        z = self.y
        localgs = np.zeros((self.n, self.permutations))
        n_1 = self.n - 1
        prange = list(range(self.permutations))
        k = self.w.max_neighbors + 1
        nn = self.n - 1
        rids = np.array([np.random.permutation(nn)[0:k] for i in prange])
        ids = np.arange(self.w.n)
        ido = self.w.id_order
        w = [self.w.weights[ido[i]] for i in ids]
        wc = [self.w.cardinalities[ido[i]] for i in ids]

        for i in range(self.w.n):
            idsi = ids[ids != i]
            np.random.shuffle(idsi)
            tmp_z = z[idsi[rids[:, 0:wc[i]]]]   
            
            if self.op == 'c':
                localgs[i] = y[i] * (w[i] * tmp_z).sum(1)
            elif self.op == 's':
                print("Not yet implemented")
            elif self.op == 'a':
                print("Not yet implemented")
            else:
                print("Not yet implemented")
            
        self.localgs = localgs

In [38]:
w = libpysal.weights.lat2W(4,4)

In [59]:
def crand(y, w, permutations=999, op = 'c'):
    """
    conditional randomization
    for observation i with ni neighbors,  the candidate set cannot include
    i (we don't want i being a neighbor of i). we have to sample without
    replacement from a set of ids that doesn't include i. numpy doesn't
    directly support sampling wo replacement and it is expensive to
    implement this. instead we omit i from the original ids,  permute the
    ids and take the first ni elements of the permuted ids as the
    neighbors to i in each randomization.
    """
    weightz = w
    z = y
    n = len(z)
    localgs = np.zeros((n, permutations))
    n_1 = n - 1
    prange = list(range(permutations))
    k = weightz.max_neighbors + 1
    nn = n - 1
    rids = np.array([np.random.permutation(nn)[0:k] for i in prange])
    ids = np.arange(weightz.n)
    ido = weightz.id_order
    w = [weightz.weights[ido[i]] for i in ids]
    wc = [weightz.cardinalities[ido[i]] for i in ids]

    for i in range(weightz.n):
        idsi = ids[ids != i]
        np.random.shuffle(idsi)
        tmp_z = z[idsi[rids[:, 0:wc[i]]]]   

        if op == 'c':
            localgs[i] = y[i] * (w[i] * tmp_z).sum(1)
            return localgs
        elif op == 's':
            print("Not yet implemented")
        elif op == 'a':
            print("Not yet implemented")
        else:
            print("Not yet implemented")

In [60]:
crand(y, w)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
zl = lag_spatial(w, y)
# Remove the suffix .sum()
g = y * zl

In [17]:
zl

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 3., 3., 2., 2., 3., 3., 2.])

In [6]:
g_local = Local_Gamma(y,w, permutations=99)
g_local.p_sim

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.48, 0.31, 0.21,
       0.39, 0.22, 0.08, 0.08, 0.18])

# Loading in default datasets

In [1]:
import os; print(os.name, os.sys.platform);
import platform; print(platform.platform())

nt win32
Windows-10-10.0.18362-SP0


In [2]:
import pysal; print(pysal.__version__)

2.2.0


In [3]:
import libpysal; print(libpysal.__version__)

4.3.0


In [34]:
from libpysal.examples import get_path

In [36]:
get_path("Bostonhsg")

Bostonhsg is not a file in any installed dataset.


In [5]:
get_path("mexicojoin.dbf")

'C:\\Users\\jeffe\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\libpysal\\examples\\mexico\\mexicojoin.dbf'

In [6]:
import libpysal
dbf = libpysal.io.open(get_path("mexicojoin.dbf"))



In [22]:
available()

                      Name                                                                                                                                                                                                                                       Description  Installed
0                    10740                                                                                                                Albuquerque, New Mexico, Census 2000 Tract Data. 10740 is the Core Based Statistical Area (CBSA) code for Albuquerque, New Mexico.       True
1                   AirBnB                                                                                                                                                                                              Airbnb rentals, socioeconomics, and crime in Chicago       True
2                  Atlanta                                                                                                                                      

In [8]:
from libpysal.examples import explain

In [45]:
from libpysal.examples import load_example
tampa1 = load_example('http://data/Commpop')

Example not available: http://data/Commpop


In [15]:
w = libpysal.io.open(libpysal.examples.get_path("Bostonhsg.gal")).read()

Bostonhsg.gal is not a file in any installed dataset.


TypeError: expected str, bytes or os.PathLike object, not NoneType

In [44]:
from libpysal.examples import explain
explain('Commpop')

In [47]:


from libpysal.examples import load_example
tampa1 = load_example('C:/Users/jeffe/pysal_data/Bostonhsg')



Example not available: C:/Users/jeffe/pysal_data/Bostonhsg


In [19]:
bostonhsg.installed()

NameError: name 'bostonhsg' is not defined

In [14]:
available()



                      Name                                                                                                                                                                                                                                       Description  Installed
0                    10740                                                                                                                Albuquerque, New Mexico, Census 2000 Tract Data. 10740 is the Core Based Statistical Area (CBSA) code for Albuquerque, New Mexico.       True
1                   AirBnB                                                                                                                                                                                              Airbnb rentals, socioeconomics, and crime in Chicago      False
2                  Atlanta                                                                                                                                      

In [43]:
from libpysal.examples import load_example
boston = load_example('Bostonhsg')
boston_ds = geopandas.read_file(tampa1.get_path('boston.shp'))
w = libpysal.weights.Queen.from_dataframe(boston_ds)
ls = losh(connectivity=w, inference="chi-square").fit(boston['NOX'])
np.round(ls.Hi[0], 3)
np.round(ls.VarHi[0], 3)

NameError: name 'losh' is not defined

In [ ]:
import geopandas as gpd
import libpysal
boston = gpd.read_file('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/boston/boston.gpkg')
w = libpysal.io.open('https://github.com/jeffcsauer/GSOC2020/raw/master/validation/data/boston/spdep_boston.gal').read()
ls = losh(connectivity=w, inference="chi-square").fit(boston['NOX'])
np.round(ls.Hi[0], 3)
np.round(ls.VarHi[0], 3)

In [31]:
tampa1.get_file_list()

['C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\.DS_Store',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.csv',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.dbf',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.geojson',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.gml',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.gpkg',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.mid',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.mif',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.shp',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.shx',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.sqlite',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.txt',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.xlsx',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston.xsd',
 'C:\\Users\\jeffe\\pysal_data\\Bostonhsg\\boston\\boston_metadata.html',
 'C:\\Users\\jeffe\\py

In [32]:
import geopandas

tampa_df = geopandas.read_file(tampa1.get_path('boston.shp'))



In [33]:
tampa_df.head()

ID  TOWN  TOWNNO   TRACT     LON      LAT       x        y  MEDV  CMEDV  \
0  1.0   0.0     0.0  2011.0 -70.955  42.2550  338.73  4679.73  24.0   24.0   
1  2.0   0.0     1.0  2021.0 -70.950  42.2875  339.23  4683.33  21.6   21.6   
2  3.0   0.0     1.0  2022.0 -70.936  42.2830  340.37  4682.80  34.7   34.7   
3  4.0   0.0     2.0  2031.0 -70.928  42.2930  341.05  4683.89  33.4   33.4   
4  5.0   0.0     2.0  2032.0 -70.922  42.2980  341.56  4684.44  36.2   36.2   

   ...    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO       B  LSTAT  \
0  ...  0.538  6.575  65.2  4.0900  1.0  296.0     15.3  396.90   4.98   
1  ...  0.469  6.421  78.9  4.9671  2.0  242.0     17.8  396.90   9.14   
2  ...  0.469  7.185  61.1  4.9671  2.0  242.0     17.8  392.83   4.03   
3  ...  0.458  6.998  45.8  6.0622  3.0  222.0     18.7  394.63   2.94   
4  ...  0.458  7.147  54.2  6.0622  3.0  222.0     18.7  396.90   5.33   

                   geometry  
0  POINT (338.730 4679.730)  
1  POINT (339.230 4683.330)  
2  POINT (340.370 4682.800)  
3  POINT (341.050 4683.890)  
4  POINT (341.560 4684.440)  

[5 rows x 24 columns]